[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
  let g:jedi#popup_on_dot = 0 
  autocmd FileType python setlocal completeopt-=preview 
'''

[[plugins]]
repo = 'ervandew/supertab'
hook_add = '''
  let g:SuperTabContextDefaultCompletionType = "context"
  let g:SuperTabDefaultCompletionType = "<c-n>"
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_i=1

